### PR TITLE
Summer 2020 Update

### LINKED ISSUE #2: Disease & Deterministic Models
Finish adding disease factors to the deterministic models used in both the infinite and finite capacities.

### LINKED ISSUE #3: Spelling and Labels
- [x] Fix the spelling of stochastic in the Finite Capacity graph.
- [ ] Resizing is causing plot labels to be cut off.
- [ ] Potentially relocate the "Theoretical Expected Capacity" label.

### LINKED ISSUE #5: Competition Exceeds Capacity
From Ethan's review:

> The green competition line can go above the actual capacity line very easily. I think that this is okay given the capacity is there for the primary species and not its main competition but though I'd let you know. More noticeably, I managed to get the blue rabbit line over the actual capacity with carrying capacity:10000, carrying capacity variation: 30%, resource abundance: 0, competitor: .3, disease month: 9, disease severity 50%. After finding more combinations I have concluded it is only possible to do if their is some sort of competition included in the model.

### PR DESCRIPTION
**Pull request by neilhatfield**
This branch contains modifications to bring the app into compliance with the BOAST Style Guide as well as working to streamline the code.

### CODE REVIEW

**Comment by neilhatfield** [comment]
This update

1.  Brings the app into compliance with the BOAST Style Guide, including accessibility and references
2.  Adds a new observation slider
3.  Adds a new layout to separate population parameter controls from factors
4.  Streamlines the code (ui.R goes from 428 lines to 418; server.R goes from 1592 lines to 454 lines
5.  Traced and resolved all of the silent warnings the original app was giving

To compare:

*   [Current version of the Population Growth Model app](https://psu-eberly.shinyapps.io/population_growth/)
*   [Proposed update of the Population Growth Model app](https://rstudio-connect.tlt.psu.edu:3939/content/206) (you will need to log into PSU's VPN)

Known Issues:

*   There are still three accessibility issues (document language missing, and 2 instances of empty links). These currently do not have a working solution.

**Review by xvwang412 — COMMENTED** [review]
I have looked through this pull request. It is a good example for us to check. The codes look much cleaner now.

**Comment by jolin0504** [comment]
I have looked through it and compared the two versions. In fact, I think the current version of app has a more tidy page. However, the proposed update version is in much better form following the style guide, which contains the buttons in the top right, the PSU logo, the order of the tab items and also the contents organized in each tab. Moreover, the proposed update version is easier to use.

**Review by Daehoon7992 — COMMENTED** [review]
1. I think it would be nicer if we add some animation feature on the sliderInputs, because users can then see what`s going on with the graphs. Plus, we might not need to add this feature on 'Starting population size', 'Carrying capacity', and 'Start month' since they don`t look like impact much with this feature.

2. On 'Finite Capacity Model', we might need to move 'Theoretical Expected Capacity' out from the graph. Because when we move sliders on 'Resource abundance' in 'Add environmental factor', it is kind of hard to see which line is 'Theoretical Expected Capacity'. So, it might need to be moved outside of the graph, for example, on the y-axis left to the graph or put that on the popover.

**Review by LeahHunt — COMMENTED** [review]
Overall, the app has definitely been improved, and I particularly like that the starting population now changes in increments of 5 to prevent the question of what a starting population of 1 means, which had bothered me in the previous version. The only two issues I see are that resizing causes ggplot labels to get cutoff, which is not necessarily something that can be easily fixed, and that under Finite Capacity stochastic is spelled stochatic in the graph title, at least in the version currently on the TLT server.

**Review by ethanwright3 — COMMENTED** [review]
The green competition line can go above the actual capacity line very easily. I think that this is okay given the capacity is there for the primary species and not its main competition but though I'd let you know. More noticeably, I managed to get the blue rabbit line over the actual capacity with carrying capacity:10000, carrying capacity variation: 30%, resource abundance: 0, competitor: .3, disease month: 9, disease severity 50%. After finding more combinations I have concluded it is only possible to do if their is some sort of competition included in the model. I can't find any style issues. In conclusion, especially after looking over the original app which I found many ways to break, this app is incredibly impressive.

**Review by jolin0504 — COMMENTED** [review]
I have looked through it and compared the two versions. In fact, I think the current version of app has a more tidy page. However, the proposed update version is in much better form following the style guide, which contains the buttons in the top right, the PSU logo, the order of the tab items and also the contents organized in each tab. Moreover, the proposed update version is easier to use.

**Review by wjw990428 — COMMENTED** [review]
The code in ui and server now looks tidy and arranged. The ui and server has been improved.Add the theoritical capacity and make the app clearer. After adding the death, also comparing before and after plot which is very good.

**Comment by lghszdnp** [comment]
Personally, I like the pattern of this app, it is tidy and clean, and when I move my mouse to the "Go" button, it changes the shape which is pretty interesting. When I playing around with the explore page and set the variable with some particular numbers the y-axis will change to some number with 'e' like: 
image
I think it will be better to use integral as the y-axis, and this is the only improvement I can see.

**Review by lghszdnp — COMMENTED** [review]
Personally, I like the pattern of this app, it is tidy and clean, and when I move my mouse to the "Go" button, it changes the shape which is pretty interesting. When I playing around with the explore page and set the variable with some particular numbers the y-axis will change to some number with 'e' like:
image
I think it will be better to use integral as the y-axis, and this is the only improvement I can see.

**Review by cgray1117 — COMMENTED** [review]
Overall, the app looks really good. I like how the explore page is separated into steps because it makes the content of the page a lot more cohesive. However, I do like the sidebar well panel format of the original app better. I think it keeps the focus on the visualization. As oppose to the updated version where the slider kind of steal the show.

**Comment by Xinyue-Tang** [comment]
Hi! I have reviewed this app and think it is really great. I like the layout of explore page and the way it works!

**Review by Xinyue-Tang — DISMISSED** [review]

**Review by pophillips — CHANGES_REQUESTED** [review]
Description File:
- [x] Add appropriate Chapter # (I believe this would go under Chapter 13)
README: 
- [x] Update Screenshot file
App Appearance:
- [x] App Short Name in top left - Can "Population Growth" fit? In my opinion simply "Pop. Growth" looks unprofessional.
- [x] "Cite App" is producing error message
- [x] On the Explore page, look at the pop up that appears when hovering over all the graphs. It is identical for each graph which to me seems redundant, it might be better to instead put the description of what the graphs are showing right after the "Step 2" label and before you pick which model to explore. The pop up I find annoying too as you cannot get rid of it if you want to point with your cursor at a specific point on the graphs.
- [x] Explore Page - Might be worth adding how the "growth rate" is calculated using the Birth rate and death rate values. Just needs to be an equation (ie GR = BR - DR), can be put on the prereq page too.
- [x] Prereq page - 6th bullet point, check if the last sentence is correct. What is "the like"?

Recommended Priority: Urgent

**Comment by pophillips** [comment]
Values as requested by Dr. Hatfield of bug with rabbit population exceeding carrying capacity in the finite capacity model:
Starting Pop: 100
Birth Rate: 1
Death Rate: 0.048
Observation Period: 24 months
Carrying Capacity/carrying capacity variation: 5000/variation 0
Resource Abundance: 3
Competitor Growth Rate: 0.3
Disease Start Month/Severity: Start Month 3/50% severity
Screen Shot 2022-07-15 at 9 40 31 AM

**Review by tarynmch — DISMISSED** [review]
This is a great working app and very educational. I really do not see any issues. I would double check the WAVE, but it looks great and works well. All I can offer are a few suggestions, but the app doesn't need any edits to be published (besides updating dates like last updated). 
I have two suggestions: I do not think it is necessary to have buttons on both the prereq and overview page. Then I see a lot of classroom potential with this app. Maybe under each plot you could put prompts, like "What do you notice when alot and alittle disease is introduced?" or "How does adding a carrying capacity impact the population?"

**Review by robchapp — CHANGES_REQUESTED** [review]
This is very close and only has minor issues, such as the date in description and readme files being incorrect. Along with minor coding issues with an outdated ggplot, the description is different in the description and the readme file. This is almost great, just small things.

**Review by robchapp — CHANGES_REQUESTED** [review]
This is very good, and super close. The only problems seem to be on the server link. The app does not work from the link, also small is the year in the readme file, and possibly spacing out the prereqs more. Otherwise super good.

**Review by robchapp — DISMISSED** [review]
Only thing is that maybe explain that the button will take you to explore, and possibly send users to prereqs first. But that is nitpicky, the app is great!

**Comment by neilhatfield** [comment]
@tarynmch Final Checks:

- [x]     Pull my updates and redeploy to the testing site.
- [x]     Email Dennis for him to double check
- [x]     Check the [App's Issues](https://github.com/EducationShinyAppTeam/Population_Growth/issues) and see which may be closed with this pull request. Add all resolved issues to the Development menu (right-hand column of the Pull Request).

**Pull request merged**
